package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, NODE_JOINED, EXECUTE_JOB, STOP_JOB, REQUEST_RESULT, TELL_RESULT, REQUEST_STATUS, TELL_STATUS,
	QUIT, BUDDY_PING, BUDDY_PONG, BUDDY_IS_ALIVE, BUDDY_YES, BUDDY_NO
}
